### ISSUE TITLE
Lighthack w/ Eos v3.0 & some other stuff...

### ISSUE THREAD

**Issue by lucien-laborderie** [Druuka/LightHack#2]
Hello Druuka, 

I've been looking into the Lighthack projects for a good month now and I've decided to build my own. I plan on building the original box as a starting point before upgrading to a more complete Lighthack (4 encoders, different pages). I have a few questions however and was wondering if you had some spare time to help !

- I plan on using it with Eos Nomad running on Win10, along with Luminosus. I'm a French student with a bit of experience using Arduino and Eos, however I don't have any experience with C++.
- I saw you recommend the Teensy 3.5 : have you tried with the Teensy 4.0 ? It seems a bit cheaper and more powerful
- every 2x40 LCD display I found required 5V whereas the Teensy only delivers 3.3V : is an external power supply required or will it work just fine ?
- the lighthack_box2 advises to "100nF capacitors between ground and the input of the switches and encoders" : is it mandatory, do you have any experience with that ?
- should I wait for Eos v3.0 to look out for compatibility issues ?
- I've made a wiring diagram based on the 4 encoders/5 pages code found on your page, does it seem correct ? (the idea is to make a complete guide for the other students wanting to give it a shot)

I am quite new to all of this so please tell me if this request is in the wrong place or anything I said is inappropriate

In any case thanks a lot for even reading this ! 👍

[Wiring Diagram.pdf](https://github.com/Druuka/LightHack/files/4397648/Wiring.Diagram.pdf)

**Comment by Druuka** [comment]
Thanks for the interest.

Teensy 4 will require a 5v power source and a level shifter in order to properly work with the display.  I would suggest using an i2c based lcd which should run on 3.3v.  You can find them at Adafruit and Sparkfun websites.
I haven’t tried the Teensy 4 yet so don’t know for sure it will work.  As long as you are using a windows machine with the drivers installed it “should” work.  

I generally haven’t used capacitors on switches in my stuff but it is a good practice.

I don’t think Eos 3.0 will cause any large problems with OSC interaction.  ETC generally adds additional support but doesn’t remove.  Things change sometimes but I haven’t seen any issues with existing workflow.  Multi-cell fixtures can be a bit of an issue.

I don’t see any issues with the wiring diagram.  Should be workable but would look into the i2c lcd or an i2c backpack for your lcd. 

Hope this helps.

Andrew

**Comment by lucien-laborderie** [comment]
Hello,

Thank you very much, I guess I'll give the 4.0 a go !

As for the LCD, the schematics at PJRC show the USB +5V connected to the
Vin pin on the board, will that do the trick to power a 5V screen ?

Lucien

**Comment by Druuka** [comment]
I usually pull power from the usb buss for the 5v sections of a project.   VIN or VUSB should get that

**Comment by Druuka** [comment]
But remember if the lcd used 5v logic you need to add a logic shifter in between or could damage the teensy

**Comment by lucien-laborderie** [comment]
Ok so I should put one of these (https://www.sparkfun.com/products/12009)
between the Teensy and the data bus lines, is that right ?
The Teensy could be damaged as the display will send 5V data back to the
board through these bus lines ?
While Vdd will get it's power directly from the USB

Thanks a lot for the tips !
